'use client';

import './globals.css';
import { Provider } from 'react-redux';

import HtmlTheme from './theme';
import { store } from '@/store/store';

// export const metadata = {
//   title: 'SIMI (Simplified Mikrotik)',
//   description: 'Generated by create next app'
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider store={store}>
      <HtmlTheme>
        <body>{children}</body>
      </HtmlTheme>
    </Provider>
  )
}
